# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: ["dev", "main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: tk_bank
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Install golang-migrate
        run: |
          curl -sSfL https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz -o migrate.tar.gz
          echo "e4174b4df74a2a0773f587974ebc84a74b40ac8e2ce0c00c92a0539c1d1d0328  migrate.tar.gz" | sha256sum -c -
          tar xzf migrate.tar.gz
          sudo mv migrate /usr/bin/migrate
          rm migrate.tar.gz
          which migrate

      - name: Run Migration
        run: make migrateup

      - name: Test
        run: make test